### ISSUE TITLE
Lectures index

### ISSUE THREAD

**Issue by sigfriedCub1990** [manjunath5496/Jewish-Nobel-Lectures#1]
This is quite interesting but for the sake of completeness we should have in the `readme.md` some sort of indexing 😃. Ex:

- [Lecture 1](jwn(1).pdf) **War and peace**. Aumann, Robert J. 8/12/2005 
**OR**
- **War and peace**. Aumann, Robert J. 8/12/2005 [Lecture 1](jwn(1).pdf)

Assign this to me and if you want I'll gladly make a **PR**.

**Comment by manjunath5496** [comment]
Read me file will be updated within today

Thanks
with warm regards
Manjunath.R

**Comment by manjunath5496** [comment]
updated sir

with warm regards

Manjunath.R
